#pragma once

// caps word
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 2500

// tap mod
#define TAPPING_TERM 250
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

// combos
#define COMBO_TERM 25
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 175

