RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_ENABLE = no

CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no 
COMBO_ENABLE = yes

CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

VPATH += keyboards/gboards

