CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

VPATH += keyboards/gboards

