SERIAL_DRIVER = vendor

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

RGB_MATRIX_SUPPORTED = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_SUPPORTED = no
RGBLIGHT_ENABLE = no

CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes

CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

VPATH += keyboards/gboards
