SERIAL_DRIVER = vendor

POINTING_DEVICE_ENABLE = no
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes

CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

VPATH += keyboards/gboards
